ID         220437625
numax         428.34
numax_e        3.593
dnu           27.086
dnu_e          0.885
Teff            5019
Teff_e            35
bp_rp       1.084425
bp_rp_e          0.1
Lum            5.321
Lum_e          0.068
Type              SG
Np                 9
Done               0
Name: 154, dtype: object
ID: 220437625


Traceback (most recent call last):
  File "/rds/projects/n/nielsemb-plato-peakbagging/george/PBjammy/ThePBjam/PBjammer.py", line 41, in Mode20
    f, s = PSD(ID, 'Text')
  File "/rds/projects/n/nielsemb-plato-peakbagging/george/PBjammy/ThePBjam/PBjammer.py", line 32, in PSD
    Lightning = pd.read_csv(f'{Directory}/LightCurves/{ID}_psd_tot.txt', names=['Frequency', 'Power', 'FrequencyAvg', 'PowerAvg'], sep=' ')
  File "/rds/homes/g/gth025/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/rds/homes/g/gth025/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/rds/homes/g/gth025/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/rds/homes/g/gth025/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/rds/homes/g/gth025/.local/lib/python3.9/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/rds/projects/n/nielsemb-plato-peakbagging/george/PBjammy/LightCurves/220437625_psd_tot.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/rds/projects/n/nielsemb-plato-peakbagging/george/PBjammy/ThePBjam/PBjammer.py", line 48, in Mode20
    f, s = PSD(ID, 'Standard')
  File "/rds/projects/n/nielsemb-plato-peakbagging/george/PBjammy/ThePBjam/PBjammer.py", line 30, in PSD
    Lightning = pd.read_csv(f'{Directory}/LightCurves/ktwo{ID}_01_kasoc-psd_slc_v1.pow', comment='#', names=['Frequency', 'Power'], sep=' ')
  File "/rds/homes/g/gth025/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/rds/homes/g/gth025/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/rds/homes/g/gth025/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/rds/homes/g/gth025/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/rds/homes/g/gth025/.local/lib/python3.9/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/rds/projects/n/nielsemb-plato-peakbagging/george/PBjammy/LightCurves/ktwo220437625_01_kasoc-psd_slc_v1.pow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/rds/projects/n/nielsemb-plato-peakbagging/george/PBjammy/ThePBjam/TheActivator.py", line 68, in LetUsBegin
    Activate(n)
  File "/rds/projects/n/nielsemb-plato-peakbagging/george/PBjammy/ThePBjam/TheActivator.py", line 41, in Activate
    Result, f, s, M = ModeResult(BigData.ID[d], BigData.Np[d], (BigData.numax[d], BigData.numax_e[d]),
  File "/rds/projects/n/nielsemb-plato-peakbagging/george/PBjammy/ThePBjam/TheActivator.py", line 23, in ModeResult
    return PBjammer.Run(ID, Np, numax=numax, dnu=dnu, teff=teff, bp_rp=bp_rp, Plot=Plot, l1=l1, Type=Type)
  File "/rds/projects/n/nielsemb-plato-peakbagging/george/PBjammy/ThePBjam/PBjammer.py", line 113, in Run
    Result, f, s, M = Mode20(ID, Np, numax=numax, dnu=dnu, teff=teff, bp_rp=bp_rp, Plot=Plot, l1=l1, Type=Type)
  File "/rds/projects/n/nielsemb-plato-peakbagging/george/PBjammy/ThePBjam/PBjammer.py", line 54, in Mode20
    f, s = PSD(ID, '3-space')
  File "/rds/projects/n/nielsemb-plato-peakbagging/george/PBjammy/ThePBjam/PBjammer.py", line 34, in PSD
    Lightning = pd.read_csv(f'{Directory}/LightCurves/ktwo{ID}_01_kasoc-psd_slc_v1.pow', comment='#', names=['Frequency', 'Power'], sep='   ')
  File "/rds/homes/g/gth025/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/rds/homes/g/gth025/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/rds/homes/g/gth025/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/rds/homes/g/gth025/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/rds/homes/g/gth025/.local/lib/python3.9/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/rds/projects/n/nielsemb-plato-peakbagging/george/PBjammy/LightCurves/ktwo220437625_01_kasoc-psd_slc_v1.pow'
